<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <UseWPF>true</UseWPF>
    <RootNamespace>Helm.Modules.AlwaysOnTop</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Helm.Core\Helm.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Helm.Tests" />
  </ItemGroup>

</Project>
