<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <UseWPF>true</UseWPF>
    <RootNamespace>Helm.Modules.Tracker</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Helm.Core.Windows\Helm.Core.Windows.csproj" />
    <ProjectReference Include="..\Helm.Modules.Tracker.Core\Helm.Modules.Tracker.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Helm.Tests" />
  </ItemGroup>

</Project>
